---
resources:
  - name: enterprise-note-git
    type: git
    icon: github
    source:
      uri: https://github.com/TeamIO-NZ/EnterpriseNote
      branch: master

  - name: golang-1.15.x-image
    type: registry-image
    icon: docker
    source:
      repository: golang
      tag: 1.15

jobs:
  - name: golang-1.15.x
    plan:
      - get: enterprise-note-git
        trigger: true
      - get: golang-1.15.x-image
        trigger: true
      - task: run
        image: golang-1.15.x-image
        config:
            platform: linux
            inputs:
              - name: enterprise-note-git
                path: go/src/go.iosoftworks.com/EnterpriseNote/
            params:
                GO111MODULE: "on"
            run:
              path: sh
              args: 
              - -c
              - |
                GOPATH=$PWD/go
                
                cd go/src/go.iosoftworks.com/EnterpriseNote
                
                go mod download

                go vet
                go build
                go install github.com/golang/mock/mockgen
                ./ci/check_go_fmt.sh
                ./ci/check_go_generate.sh
                go test -v
    on_success:
      do:
      - task: notify-success
        config:
          platform: linux
          image_resource: &apline
            type: docker-image
            source:
              repository: alpine
              tag: edge
          run:
            path: sh
            args:
            - ./ci/notify_discord.sh
            - "((hook-url))"
            - enterprise-note
            - success
        
    on_abort:
      do:
      - task: notify-abort
        config:
          platform: linux
          image_resource: *apline
          run:
            path: sh
            args:
            - ./ci/notify_discord.sh
            - "((hook-url))"
            - enterprise-note
            - abort
    on_failure:
      do:
      - task: notify-failure
        config:
          platform: linux
          image_resource: *apline
          run:
            path: sh
            args:
            - ./ci/notify_discord.sh
            - "((hook-url))"
            - enterprise-note
            - failure
    on_error:
      do:
      - task: notify-error
        config:
          platform: linux
          image_resource: *apline
          run:
            path: sh
            args:
            - ./ci/notify_discord.sh
            - "((hook-url))"
            - enterprise-note
            - error
